name: Custom Action composite
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: print files
        run: ls -la 
      - name: setup node and dependencies
        uses: ./.github/actions/composite-cache
        with:
          node-version: '20.x'
          working-directory: '.'
      - name: Run test
        run: npm test
        working-directory: '.'
      - name: Run build
        run: npm run build
        working-directory: '.'